[2023-05-18 02:29:49,057] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:33:03,424] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:42:42,349] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:42:51,111] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 02:42:51,111] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 02:45:37,607] INFO [django.utils.autoreload.trigger_reload:266 autoreload]
[2023-05-18 02:45:38,204] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:46:09,038] INFO [django.utils.autoreload.trigger_reload:266 autoreload]
[2023-05-18 02:46:09,666] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:58:02,299] INFO [django.utils.autoreload.trigger_reload:266 autoreload]
[2023-05-18 02:58:02,911] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:58:40,901] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:59:01,038] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 02:59:18,948] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 02:59:18,948] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:00:50,697] ERROR [django.security.DisallowedHost.response_for_exception:125 exception]
Traceback (most recent call last):
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'google.com:443'. You may need to add 'google.com' to ALLOWED_HOSTS.
[2023-05-18 03:00:51,913] ERROR [django.security.DisallowedHost.response_for_exception:125 exception]
Traceback (most recent call last):
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/lighthouse/.local/lib/python3.8/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '110.242.68.4'. You may need to add '110.242.68.4' to ALLOWED_HOSTS.
[2023-05-18 03:06:53,110] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 03:07:05,227] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:07:05,227] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:08:39,809] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 03:08:47,879] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:08:47,879] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:09:43,958] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 03:09:45,388] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:09:45,388] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:09:45,402] INFO [djangoblog.load_sidebar:82 blog_tags]
[2023-05-18 03:09:45,402] INFO [djangoblog.load_sidebar:82 blog_tags]
[2023-05-18 03:09:50,973] INFO [djangoblog.seo_processor:13 context_processors]
[2023-05-18 03:09:50,973] INFO [djangoblog.seo_processor:13 context_processors]
[2023-05-18 03:09:52,437] INFO [djangoblog.seo_processor:13 context_processors]
[2023-05-18 03:09:52,437] INFO [djangoblog.seo_processor:13 context_processors]
[2023-05-18 03:09:53,276] INFO [djangoblog.seo_processor:13 context_processors]
[2023-05-18 03:09:53,276] INFO [djangoblog.seo_processor:13 context_processors]
[2023-05-18 03:52:11,710] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 03:52:40,741] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:52:40,741] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:53:19,744] INFO [django.utils.autoreload.run_with_reloader:677 autoreload]
[2023-05-18 03:53:22,542] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:53:22,542] INFO [djangoblog.seo_processor:16 context_processors]
[2023-05-18 03:53:22,551] INFO [djangoblog.load_sidebar:82 blog_tags]
[2023-05-18 03:53:22,551] INFO [djangoblog.load_sidebar:82 blog_tags]
